language: python
python:
    - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc python-socksipy libssl-dev swig -qq
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.10/ssdeep-2.10.tar.gz
    - tar -zxvf ssdeep-2.10.tar.gz
    - cd ssdeep-2.10
    - ./configure && make
    - sudo make install
    - cd ..
install:
    - pip install -r requirements.txt
script:
    - echo "exit" | python viper.py
